In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
movie = pd.read_csv("/mnt/c/Users/ssait/Downloads/movie.csv")

In [4]:
user = pd.read_csv("/mnt/c/Users/ssait/Downloads/user.csv")

In [5]:
ratings = pd.read_csv("/mnt/c/Users/ssait/Downloads/ratings.csv")

In [6]:
user.head()

   user id  age gender  occupation zip code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [14]:
user.shape

(943, 5)

In [7]:
user.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [18]:
user.describe()

          user id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

In [20]:
movie.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [22]:
movie.columns

Index(['movie id', 'movie title', 'release date', 'Action', 'Adventure',
       'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama',
       'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance',
       'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='str')

In [11]:
# new_columns = movie.columns[3:]
# new_columns
new_df = movie.iloc[:, 3:]
new_df

,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1676,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1677,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1678,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1679,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [16]:
genre_count = new_df.sum()
genre_count

Action         251
Adventure      135
Animation       42
Childrens      122
Comedy         505
Crime          109
Documentary     50
Drama          725
Fantasy         22
Film-Noir       24
Horror          92
Musical         56
Mystery         61
Romance        247
Sci-Fi         101
Thriller       251
War             71
Western         27
dtype: int64

In [17]:
genre_count.sort_values(ascending=True)

Fantasy         22
Film-Noir       24
Western         27
Animation       42
Documentary     50
Musical         56
Mystery         61
War             71
Horror          92
Sci-Fi         101
Crime          109
Childrens      122
Adventure      135
Romance        247
Action         251
Thriller       251
Comedy         505
Drama          725
dtype: int64

In [12]:
movie["Number of Genres"] = new_df.sum(axis=1)

In [14]:
movie

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,1678,Mat' i syn,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1676,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1677,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
1678,1681,You So Crazy,1-Jan-94,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1679,1682,Scream of Stone (Schrei aus Stein),8-Mar-96,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
new_df.sum().sort_values(ascending=False)

Drama          725
Comedy         505
Thriller       251
Action         251
Romance        247
Adventure      135
Childrens      122
Crime          109
Sci-Fi         101
Horror          92
War             71
Mystery         61
Musical         56
Documentary     50
Animation       42
Western         27
Film-Noir       24
Fantasy         22
dtype: int64

In [23]:
genres = new_df.columns

In [25]:
movie["Number of Genres"] = movie.loc[:, genres].sum(axis=1)

In [27]:
movie.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,3

In [30]:
movie[movie["Number of Genres"]>1]

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,3
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,3
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,3
6,7,Twelve Monkeys,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666,1669,MURDER and murder,20-Jun-97,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,3
1667,1670,Tainted,1-Feb-98,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,2
1670,1673,Mirage,1-Jan-95,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,2
1676,1679,B. Monkey,6-Feb-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,2
1677,1680,Sliding Doors,1-Jan-98,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2

In [37]:
movie.loc[:,["movie id", "movie title","release date", "Number of Genres"]]

,movie id,movie title,release date,Number of Genres
0,1,Toy Story,1-Jan-95,6
1,2,GoldenEye,1-Jan-95,6
2,3,Four Rooms,1-Jan-95,2
3,4,Get Shorty,1-Jan-95,6
4,5,Copycat,1-Jan-95,6
...,...,...,...,...
1675,1678,Mat' i syn,6-Feb-98,2
1676,1679,B. Monkey,6-Feb-98,4
1677,1680,Sliding Doors,1-Jan-98,4
1678,1681,You So Crazy,1-Jan-94,2
1679,1682,Scream of Stone (Schrei aus Stein),8-Mar-96,2

In [34]:
movie["Number of Genres"] = movie.loc[:, genres].sum(axis=1)

In [38]:
movie["Number of Genres"] = movie.iloc[:, 3:].sum(axis=1)

In [40]:
movie.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,9
1,2,GoldenEye,1-Jan-95,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,9
2,3,Four Rooms,1-Jan-95,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,3
3,4,Get Shorty,1-Jan-95,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,9
4,5,Copycat,1-Jan-95,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,9

In [42]:
ratings.head()

   user id  movie id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [65]:
df_merge  = movie.merge(ratings, on='movie id', how ='inner')

In [46]:
df_merge.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,308,4,887736532
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,287,5,875334088
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,148,4,877019411
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,280,4,891700426
4,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,66,3,883601324

In [48]:
genres

Index(['Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
       'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'],
      dtype='str')

In [53]:
for i in genres:
    print(i,':' , df_merge[df_merge[i]==1].rating.mean())

Action : 3.480245417953027
Adventure : 3.503526503308369
Animation : 3.5766990291262135
Childrens : 3.3532442216652742
Comedy : 3.3940734781442745
Crime : 3.6322780881440098
Documentary : 3.6728232189973613
Drama : 3.6873793708484772
Fantasy : 3.2152366863905324
Film-Noir : 3.9215233698788228
Horror : 3.2903893172841827
Musical : 3.521396851029471
Mystery : 3.63813155386082
Romance : 3.621704948358255
Sci-Fi : 3.5607227022780834
Thriller : 3.5090069495245064
War : 3.815811874866993
Western : 3.6132686084142396

In [ ]:
# df_merge = movie.merge(ratings, on = 'movie id', how = 'outer')
# df_merge.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,308,4,887736532
1,1,Toy Story,1-Jan-95,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,287,5,875334088
2,1,Toy Story,1-Jan-95,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,148,4,877019411
3,1,Toy Story,1-Jan-95,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,280,4,891700426
4,1,Toy Story,1-Jan-95,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9.0,66,3,883601324

In [ ]:
# df_merge = user.merge(ratings, on = 'user id', how = 'inner')
# df_merge.head()

   user id  age gender  occupation zip code  movie id  rating  timestamp
0        1   24      M  technician    85711        61       4  878542420
1        1   24      M  technician    85711       189       3  888732928
2        1   24      M  technician    85711        33       4  878542699
3        1   24      M  technician    85711       160       4  875072547
4        1   24      M  technician    85711        20       4  887431883

In [67]:
df_merge.head()

,movie id,movie title,release date,Action,Adventure,Animation,Childrens,Comedy,Crime,Documentary,...,Mystery,Romance,Sci-Fi,Thriller,War,Western,Number of Genres,user id,rating,timestamp
0,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,308,4,887736532
1,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,287,5,875334088
2,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,148,4,877019411
3,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,280,4,891700426
4,1,Toy Story,1-Jan-95,0,0,1,1,1,0,0,...,0,0,0,0,0,0,9,66,3,883601324

In [69]:
df_merge.groupby(['movie title'])[['rating']].mean().reset_index()

                          movie title    rating
0                 'Til There Was You   2.333333
1                              1-900   2.600000
2                     101 Dalmatians   2.908257
3                       12 Angry Men   4.344000
4                                 187  3.024390
...                               ...       ...
1652                      Young Guns   3.207921
1653                   Young Guns II   2.772727
1654  Young Poisoner's Handbook, The   3.341463
1655                Zeus and Roxanne   2.166667
1656     Á köldum klaka (Cold Fever)   3.000000

[1657 rows x 2 columns]